USE boulderdash;

INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','player',          'soil',            'soil',            'diamond',         'soil',            'rock',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'diamond',         'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'rock',            'void',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'rock',            'soil',            'soil',            'void',            'enemy',           'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'soil',            'void',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'rock',            'soil',            'soil',            'soil',            'void',            'soil',            'soil',            'soil',            'soil',            'void',            'rock',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'rock',            'soil',            'rock',            'soil',            'destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','destructibleWall','border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'diamond',         'soil',            'soil',            'soil',            'destructibleWall','soil',            'diamond',         'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'soil',            'soil',            'soil',            'soil',            'destructibleWall','soil',            'soil',            'soil',            'soil',            'void',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'soil',            'soil',            'soil',            'soil',            'destructibleWall','rock',            'soil',            'soil',            'soil',            'enemy',           'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'rock',            'soil',            'soil',            'rock',            'destructibleWall','soil',            'soil',            'soil',            'soil',            'rock',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','soil',            'soil',            'soil',            'diamond',         'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('border','border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border');