USE boulderdash;

INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'soil',            'void',            'rock',            'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'rock',            'diamond',         'soil',            'rock',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'rock',            'soil',            'soil',            'soil',            'soil',            'soil',            'rock',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'soil',            'soil',            'soil',            'player',          'soil',            'rock',            'soil',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'soil',            'rock',            'soil',            'soil',            'rock',            'diamond',         'void',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'soil',            'soil',            'soil',            'soil',            'soil',            'rock',            'soil',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'soil',            'diamond',         'soil',            'soil',            'soil',            'soil',            'soil',            'soil',            'border');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border',          'border');