USE boulderdash;

INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','PLAYER',          'SOIL',            'SOIL',            'DIAMOND',         'SOIL',            'ROCK',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'DIAMOND',         'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'ROCK',            'VOID',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'ROCK',            'SOIL',            'SOIL',            'VOID',            'ENEMY',           'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'SOIL',            'VOID',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'ROCK',            'SOIL',            'SOIL',            'SOIL',            'VOID',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'VOID',            'ROCK',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'ROCK',            'SOIL',            'ROCK',            'SOIL',            'DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','DESTRUCTIBLEWALL','BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'DIAMOND',         'SOIL',            'SOIL',            'SOIL',            'DESTRUCTIBLEWALL','SOIL',            'DIAMOND',         'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'DESTRUCTIBLEWALL','SOIL',            'SOIL',            'SOIL',            'SOIL',            'VOID',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'DESTRUCTIBLEWALL','ROCK',            'SOIL',            'SOIL',            'SOIL',            'ENEMY',           'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'ROCK',            'SOIL',            'SOIL',            'ROCK',            'DESTRUCTIBLEWALL','SOIL',            'SOIL',            'SOIL',            'SOIL',            'ROCK',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','SOIL',            'SOIL',            'SOIL',            'DIAMOND',         'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level2(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15) VALUES ('BORDER','BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER');