USE boulderdash;

INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'SOIL',            'VOID',            'ROCK',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'ROCK',            'DIAMOND',         'SOIL',            'ROCK',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'ROCK',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'ROCK',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'SOIL',            'SOIL',            'SOIL',            'PLAYER',          'SOIL',            'ROCK',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'SOIL',            'ROCK',            'SOIL',            'SOIL',            'ROCK',            'DIAMOND',         'VOID',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'ROCK',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'SOIL',            'DIAMOND',         'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'SOIL',            'BORDER');
INSERT INTO level1(col1,col2,col3,col4,col5,col6,col7,col8,col9,col10) VALUES ('BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER',          'BORDER');